### ISSUE TITLE
Add 5.3 support

### ISSUE THREAD

**Issue by MrArbitrary** [arbitrarygames/LandscapeSplineHelper#4]
Per a request on https://www.unrealengine.com/marketplace/en-US/product/landscape-spline-helper-plugin/questions.

**Comment by anttin2020** [comment]
Hi!
Thanks for your reply on Marketplace :)
I would try it myself but I am no C++ coder and when I tried to compile it with runuat, it gave code errors so I cannot fix it.
So I hope you will update it, it would be very useful with PCG :)

BTW, I installed it in Engine/Plugins and in 5.2 it works fine, is that ok or should it be installed in project? I prefer engine level as that way it is easy to use in any project but I don't know if there is some possible problems with using it like that.

Thank you!

**Comment by MrArbitrary** [comment]
> Hi! Thanks for your reply on Marketplace :) I would try it myself but I am no C++ coder and when I tried to compile it with runuat, it gave code errors so I cannot fix it. So I hope you will update it, it would be very useful with PCG :)
> 
> BTW, I installed it in Engine/Plugins and in 5.2 it works fine, is that ok or should it be installed in project? I prefer engine level as that way it is easy to use in any project but I don't know if there is some possible problems with using it like that.
> 
> Thank you!

I'd recommend using project level as that is what I tested it in. Additionally, if you collaborate with other people on your project, they'll need the plugin too. Since the plugin provides blueprint nodes, they won't be able to open the project until they install it too. But if you install the plugin at the project level, you can circumvent this issue since everyone with the project has the same plugins.

**Comment by MrArbitrary** [comment]
https://github.com/arbitrarygames/LandscapeSplineHelper/releases/tag/v1.0.2
